{{- if not .Values.redis.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "forge.fullname" . }}-redis
  labels:
    {{- include "forge.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "forge.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
